name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - name: Download GLuaLint
      run: curl -o glualint.zip -L https://github.com/FPtje/GLuaFixer/releases/download/1.11.2/glualint-1.11.2-linux.zip
    - name: Unzip GLuaLint
      run: unzip glualint.zip
    - name: Lint lua files
      run: ./glualint lua
